### ISSUE TITLE
IE10 component issue

### ISSUE THREAD

**Issue by evax** [montagejs/montage#1477]
The application I'm working on crashes on IE10 just after loading:
https://github.com/montagejs/montage/blob/master/ui/component.js#L1080

`children` being undefined or null

It works fine in IE11 (and Chrome, FF and Safari)

**Comment by rayshan** [comment]
Closing as we're supporting evergreen browsers (IE11+).

**Comment by cdebost** [comment]
@hthetiot @benoitmarchant I don't think we need to support IE10.

**Comment by marchant** [comment]
Correct IE11 is the oldest we care about now
