### ISSUE TITLE
Alias improvements

### ISSUE THREAD

**Issue by rayshan** [montagejs/montage#1517]
- [ ] alias should expose to within component itself just like it would to the outside world, e.g.:

``` json
{
  ":iteration": {
    "alias": "@repetition:iteration"
  },
  "bindings": {
    "property": {"<-": "@owner:iteration.object.key"}
  }
}
```
- [ ] alias should allow deeper references; currently only `@repetition:iteration` works, 
  `@repetition:iteration.object` doesn't work, fix should be in https://github.com/montagejs/montage/blob/master/core/serialization/alias.js#L33

**Comment by cdebost** [comment]
Hmm, I don't know what the point of this would be.

In the first example, I can't think of a use case where you would want to define an iteration symbol on a component from the outside; if the component needs to have an iteration symbol for its own purposes it should define it itself, and if it doesn't use it itself then there is not much point to the alias in the first place.

The example given is a little strange as well; aliases are intended to be top-level objects sitting next to components and objects. An alias is part of the way a component can describe its public API, and I don't think allowing a component to define an alias on its child makes a lot of sense or is particularly useful.

As for # 2, allowing deeper references doesn't really make sense either., The real reason aliases come in handy is that you can use them to define a symbol on a component (like :iteration), which you cannot do with a property or binding. But a path like `@repetition:iteration.object` is not a fixed value. If you define an alias like this at the root of a component, what would the value be? The first of repetition's content? A random value? And if you wanted to use this to define an alias on a repeated component (e.g. the child of a repetition), you could just make a binding like this:
```json
{
  "foo": {
    "prototype": "repeated-component.reel",
    "values": {
      "iteration": {"<-": "@repetition:iteration"},
      "object": {"<-": "iteration.object"}
    }
}
```

**Comment by rayshan** [comment]
It's been a while...

I agree I can't think of why # 1 would make sense now.

For # 2, `@repetition:iteration.object` is a fixed value for the current iteration right? Here's a use case:

https://github.com/konturlabs/contour-framework/blob/b25058c2d7b75533db95c17ee98b1c470eadb499/ui/user/user-info.reel/user-info.html#L35-L50

Instead of `@accountButtons:iteration.object.url`, we can alias `:url` to `:iteration.object.url` and write `@accountButtons:url`. It's just sugar. Value is debatable.

On a separate note, I wonder why we have `alias` at all? It's only ever used to alias the current iteration on a repetition-like component. It's not useful to alias any regular property - just use a getter for that. It's another thing engineers have to learn. Is it possible to just have special `Component.prototype.iteration` interface to represent the current iteration?

**Comment by cdebost** [comment]
In the contour example, the reason I think the value is almost none is that you could do this instead:
```json
"bindings": {
  "object": {"<-": "@accountButtons:iteration.object"},
  "href": {"<-": "object.url"},
  "target": {"<-": "object.target"}
}
```

As I recently discovered by working on the montage deserializer, `alias` actually cannot be used for regular properties - parser throws an error if you try to make an alias with a key that does not start with `:`. So it is really exclusively used for template values. Definitely could be made simpler.

Anyway, thanks for the clarification. I will close this and see if I can improve the template value interface while I rewrite the deserializer.

**Comment by rayshan** [comment]
That example is certainly better. In the case of a list with complicated list items, containing many inner components needing access to `repetition:iteration.object`, this create a lot more bindings though. But I agree this ticket is probably not worth investigating.
