### ISSUE TITLE
Reduce global scope pollution

### ISSUE THREAD

**Issue by rayshan** [montagejs/montage#1538]
We currently attach a lot of properties to `window`. It's not clear when to check `window` and when not to, e.g. one would think to check `montage` instance for `defaultEventManager`. There's risk for collision, and this makes node implementation difficult as there's `global`, not `window`. We should attach `montage` to `window` and everything else to `montage`.

Discussed w/ @thibaultzanini

**Comment by hthetiot** [comment]
17.0x use global now instead of window.
