### ISSUE TITLE
Remove hardcoded dependencies, use npm

### ISSUE THREAD

**Issue by rayshan** [montagejs/montage#1539]
- [ ] `date-converter.js`

The original we're using is abandoned and hasn't been updated since 2007. Here's a maintained fork with many perf & bug fixes with smaller file size:
https://github.com/abritinthebay/datejs

Also should install via npm for dependency management then wrap as montage object.

Alternatively consider moments.js, not a drop-in replacement
http://momentjs.com
- [ ] `messageformat.js`

https://github.com/SlexAxton/messageformat.js/
- [x] mr hard coded in packages dir
- [x] jshint https://github.com/montagejs/montage/blob/master/core/jshint.js
- [ ] classlist

https://github.com/eligrey/classList.js
https://github.com/montagejs/montage/blob/master/core/dom.js#L92
- [ ] UUID
  https://github.com/broofa/node-uuid
  https://github.com/montagejs/montage/blob/master/core/uuid.js

**Comment by marchant** [comment]
Sophiacom has used mommentjs for their montag calendar date picker, one more reason to consider it.
