### ISSUE TITLE
composer/key-composer does not fire events

### ISSUE THREAD

**Issue by cdebost** [montagejs/montage#1571]
Tested keyPress, longKeyPress, keyRelease, none work.

On latest version of Chrome and Firefox for Windows 8.1 and Chrome for OSX with Montage 0.13.7 and later.

**Comment by cdebost** [comment]
Not working on Montage 0.13.7 and later

**Comment by cdebost** [comment]
The key-composer tests fail on my machine. Also interestingly the key-composer spec is not currently included in the list of tests

**Comment by cdebost** [comment]
The key composer tests pass, so it must have something to do with the use of testPage.keyEvent in the spec vs actual user input in a real MJS project

**Comment by hthetiot** [comment]
Fixed by #1907
