### ISSUE TITLE
PressComposer registers press after native scrolling on iOS

### ISSUE THREAD

**Issue by rayshan** [montagejs/montage#1583]
When PressComposer is used, on iOS (haven't tested other touch-enabled browsers), if you scroll, starting at a component that listens for its press events, press events are registered after scrolling.

For example, AbstractCheckbox uses PressComposer. Scrolling starting with your finger on the checkbox, once finger is lifted, checkbox is checked.

![slack_for_ios_upload_720](https://cloud.githubusercontent.com/assets/3760840/8814629/83148900-2fc3-11e5-9570-d36fdd3dce83.jpg)

In this view, the div starting at "Language" to bottom of page is scrollable by setting overflow to scroll in CSS.

According to @thibaultzanini, we may need to set a radius to cancel press outside of the element.

cc @romancortes @marchant 

Note scrolling in Flow is not impacted by this bug.

**Comment by marchant** [comment]
I think Thibault's right, Javier?


montagestudio.com
 	
Benoit Marchant
CEO & Founder
1290 Oakmead Parkway,y Ste 111
Sunnyvale, CA 94085
(1) 408.621.4874 mobile
Profile | @benoitmarchant

**Comment by thibaultzanini** [comment]
Fixed
