### ISSUE TITLE
Montage does not run when installed with npm v3

### ISSUE THREAD

**Issue by rayshan** [montagejs/montage#1611]
npm v3 introduced a deduped and flattened `node_modules` directory:
https://github.com/npm/npm/releases/tag/v3.0.0

With a fresh git clone of montage, after npm install using npm v3.3.4, this is the `node_modules` directory structure:

```
/node_modules
    /balanced-match
    /brace-expansion
    /cli
    /collections
        /listen
        /CHANGES.md
        /collections.js
        /deque.js
        /dict.js
        /fast-map.js
        /...
    /concat-map
    /console-browserify
    /core-util-is
    /domelementtype
    /domhandler
    /domutils
    /exit
    /frb
    /glob
    /htmlparser2
    /inflight
    /inherits
    /isarray
    /jshint
    /lru-cache
    /mime
    /mimeparse
    /minimatch
    /montage
    /montage-testing
    /mousse
    /mr
    /once
    /path-is-absolute
    /q
    /q-io
    /qs
    /readable-stream
    /shelljs
    /sigmund
    /string_decoder
    /underscore
    /url2
    /weak-map
    /wrappy
```

Note that `collections` directory no longer have another `node_modules` nested in it.

When serving `index.html`, this is the error:

![screen shot 2015-09-24 at 12 10 50 pm](https://cloud.githubusercontent.com/assets/3760840/10083900/62c801a2-62b5-11e5-9a4a-e1d5958ad743.png)

I'm guessing somewhere the path is hardcoded. May be more of an issue with mr.

**Comment by rayshan** [comment]
FYI it's safe to upgrade node to 4.x, just not npm to 3.x.

**Comment by rayshan** [comment]
Node v5 is out, which uses npm v3 by default:
https://nodejs.org/en/blog/release/v5.0.0/

**Comment by hthetiot** [comment]
+1

**Comment by marchant** [comment]
yes, we still have to address that

**Comment by pchaussalet** [comment]
FYI, there is a simple workaround to this issue:
Add `legacy-bundling=true` in the .npmrc file at the root of the project.

**Comment by marchant** [comment]
Thanks Pierre, good to know!

**Comment by hthetiot** [comment]
See https://github.com/montagejs/mr/commit/f1d7f055ab2fda0b3fac114b4b62a4d13b85ae41
