### ISSUE TITLE
montage.js uses Map without requiring it

### ISSUE THREAD

**Issue by rayshan** [montagejs/montage#1693]
Environment: 
Galaxy S4, Android 4.4.2, factory settings
`"Mozilla/5.0 (Linux; Android 4.4.2; SAMSUNG-SGH-I337 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36"`

Code:
https://github.com/montagejs/montage/blob/master/montage.js#L6

Error: `Uncaught ReferenceError: Map is not defined`

**Comment by hthetiot** [comment]
no anymore
