### ISSUE TITLE
Cannot resolve modules

### ISSUE THREAD

**Issue by rayshan** [montagejs/montage#1694]
Environment: 
Galaxy S4, Android 4.4.2, factory settings
`"Mozilla/5.0 (Linux; Android 4.4.2; SAMSUNG-SGH-I337 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36"`

Error: `GET file:///android_asset/www/undefined montage.js:570`

Code:
https://github.com/montagejs/montage/blob/master/montage.js#L694 `resolve` function returns `undefined`; it does return the correct path in recent Chrome.

**Comment by hthetiot** [comment]
cannot reproduce via Galaxy S6 Chrome 56
