### ISSUE TITLE
Installation is incomplete

### ISSUE THREAD

**Issue by MichelFloyd** [montagejs/montage#1723]
Following the installation instructions in this project's readme results in a non-functional app that errors in the js console with:

> q.js:132 Uncaught Error: Can't require module "ui/loader.reel/loader" via ""
> because Can't XHR "http://localhost:8083/ui/loader.reel/loader.js"

The entire `loader.reel` directory is missing from `/ui`

**Comment by hthetiot** [comment]
Instruction here worked for me:
- https://github.com/montagejs/montage/blob/master/README.md#quick-setup
