### ISSUE TITLE
Add property assignment to Bindings block that will replace properties

### ISSUE THREAD

**Issue by hthetiot** [montagejs/montage#1820]
Add property assignment to Bindings block that will replace properties
The ability to assign a value derived from another object in the serialization is missing. By adding a new way to make one-time assignment to bindings, we can later remove the properties block:

      "cnn": {
            "prototype": "ui/tv/tv-cnn.reel",
            "properties": {
                "element": {"#": "cnn"},
                "identifier": "cnn"
            },
            "bindings": {
                "isVisible": {"<-": "@owner.isVisible"}
            }
        },

Becomes

      "cnn": {
            "prototype": "ui/tv/tv-cnn.reel",
            "values": {
                "element": {"=": "#cnn"},
                "identifier": {"=": "cnn"},
                "foo": "FOO",
                "isVisible": {"<-": "@owner.isVisible"},
                "propA.probB": {"=": "@owner.blah.baz"}
            }
        },

**Comment by cdebost** [comment]
@hthetiot Fixed by #1827?

**Comment by thibaultzanini** [comment]
@cdebost Yes Fixed by #1827
