### ISSUE TITLE
Remove didCreate() API

### ISSUE THREAD

**Issue by cdebost** [montagejs/montage#1834]
The Montage Reviver calls didCreate() or the constructor() on a newly instantiated Montage object, depending on which is available. We should completely remove the didCreate() API, as it is called the exact same way as the constructor, adding no extra value. Additionally, defining a didCreate function on a Montage prototype will also unintuitively cause the constructor function to not be called when instantiated.

**Comment by marchant** [comment]
Agreed, this was necessary pre-use of constructors, less now as one can override its constructor to know
